version: "3.9"

services:
  backend:
    build: .
    container_name: csms-backend
    restart: unless-stopped

    # ↔︎  Externe API-poort
    ports:
      - "5062:5062"

    # ↔︎  Live-reload + code-volume
    volumes:
      - .:/app

    # ↔︎  Influx-config uit env (kan je eenvoudig wisselen)
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=my-token
      - INFLUX_ORG=v2x_org
      - INFLUX_BUCKET=v2x_bucket

    depends_on:
      - influxdb

    command: >
      uvicorn main:app --host 0.0.0.0 --port 5062 --reload

  influxdb:
    image: influxdb:2.7
    container_name: v2x-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=v2x_org
      - DOCKER_INFLUXDB_INIT_BUCKET=v2x_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    volumes:
      - influxdb_data:/var/lib/influxdb2

volumes:
  influxdb_data:
